import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import '../main.dart';

class SettingsScreen extends StatefulWidget {
  const SettingsScreen({super.key});

  @override
  State<SettingsScreen> createState() => _SettingsState();
}

class _SettingsState extends State<SettingsScreen> {
  bool _sound = true;
  bool _haptic = true;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: C.surface,
      appBar: AppBar(
        backgroundColor: C.surface,
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: C.ink, size: 20),
          onPressed: () => Navigator.pop(context),
        ),
        title: Text('Settings',
            style: GoogleFonts.inter(
                fontSize: 17, fontWeight: FontWeight.w700, color: C.ink)),
        centerTitle: true,
        bottom: PreferredSize(
          preferredSize: const Size.fromHeight(1),
          child: Container(height: 1, color: C.div),
        ),
      ),
      body: ListView(
        children: [
          // ── Game section ──────────────────────────────────────────
          _sectionHeader('Game'),
          _toggleRow('Sound', _sound, (v) => setState(() => _sound = v)),
          _divider(),
          _toggleRow(
              'Haptic Feedback', _haptic, (v) => setState(() => _haptic = v)),
          _divider(),
          _navRow('Theme', 'Light'),
          const SizedBox(height: 8),

          // ── AI section ────────────────────────────────────────────
          _sectionHeader('AI'),
          _navRow('AI Model', 'Claude (Default)'),
          Padding(
            padding: const EdgeInsets.fromLTRB(16, 8, 16, 8),
            child: Text(
              'Life events are generated by AI\nbased on your stats and history.',
              style: GoogleFonts.inter(
                  fontSize: 12, color: C.inkFaint, height: 1.5),
            ),
          ),
          const SizedBox(height: 8),

          // ── Data section ──────────────────────────────────────────
          _sectionHeader('Data'),
          _navRow('Export Life Summary', null),
          _divider(),
          // Delete — red
          InkWell(
            onTap: () {},
            child: Padding(
              padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
              child: Text('Delete All Data',
                  style: GoogleFonts.inter(
                      fontSize: 15,
                      color: Colors.red.shade600,
                      fontWeight: FontWeight.w500)),
            ),
          ),
          const SizedBox(height: 8),

          // ── About section ─────────────────────────────────────────
          _sectionHeader('About LifeArc'),
          _infoRow('Version', '1.0.0'),
        ],
      ),
    );
  }

  Widget _sectionHeader(String title) => Padding(
        padding: const EdgeInsets.fromLTRB(16, 20, 16, 6),
        child: Text(title,
            style: GoogleFonts.inter(
                fontSize: 12,
                fontWeight: FontWeight.w600,
                color: C.inkFaint,
                letterSpacing: 0.5)),
      );

  Widget _toggleRow(String label, bool val, ValueChanged<bool> onChanged) =>
      Padding(
        padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 4),
        child: Row(children: [
          Expanded(
              child: Text(label,
                  style: GoogleFonts.inter(
                      fontSize: 15,
                      color: C.ink,
                      fontWeight: FontWeight.w500))),
          Switch.adaptive(
            value: val,
            onChanged: onChanged,
            activeColor: C.health,
          ),
        ]),
      );

  Widget _navRow(String label, String? trailing) => InkWell(
        onTap: () {},
        child: Padding(
          padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
          child: Row(children: [
            Expanded(
                child: Text(label,
                    style: GoogleFonts.inter(
                        fontSize: 15,
                        color: C.ink,
                        fontWeight: FontWeight.w500))),
            if (trailing != null) ...[
              Text(trailing,
                  style: GoogleFonts.inter(fontSize: 14, color: C.inkFaint)),
              const SizedBox(width: 4),
            ],
            const Icon(Icons.chevron_right, color: C.inkFaint, size: 20),
          ]),
        ),
      );

  Widget _infoRow(String label, String value) => Padding(
        padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
        child: Row(children: [
          Expanded(
              child: Text(label,
                  style: GoogleFonts.inter(
                      fontSize: 15,
                      color: C.ink,
                      fontWeight: FontWeight.w500))),
          Text(value,
              style: GoogleFonts.inter(fontSize: 14, color: C.inkFaint)),
        ]),
      );

  Widget _divider() =>
      const Divider(height: 1, indent: 16, endIndent: 16, color: C.div);
}
